name: Fireworkshop
main: com.alto.fireworkshop.Main
version: 1.7.2.1
description: Custom Fireworks Plugin [1.7.2]
authors: [Alto]
website: http://www.exloki.com/
commands:
  firework:
    description: Create custom fireworks!
    aliases: [fwk]
    permission: firework.use
permissions:
  firework.use:
    description: Allows access to /firework
    default: op