name: Firework
main: com.github.exloki.firework.Fireworks
version: 0.1.0
description: Custom Fireworks Plugin [1.6.4]
authors: [Exloki]
website: http://www.exloki.com/
commands:
  firework:
    description: Create custom fireworks!
    aliases: [fwk]
    permission: firework.use
permissions:
  firework.use:
    description: Allows access to /firework
    default: op
    test hhehehheheh